### ISSUE TITLE
about namespace wng

### ISSUE THREAD

**Issue by cloudsan** [WatershedArts/Footfall#1]
Dear author,
I cloned your project and try to build it on my raspberrypi,
but when I try to make it, it shows the error msg:wng is not a namespace-name
it works after I remove line 17 in ofApp.h, is it ok?

**Comment by DHaylock** [comment]
Hi @cloudsan 

No worries, yeah thats fine I need to remove the reference.
It was for a CSV module where you could store it in case the network goes down.
I'll commit the changes next week.

Thank you for spotting this, let me know how it goes.

Best

David
