### ISSUE TITLE
Save detection photo?

### ISSUE THREAD

**Issue by gorkemhacioglu** [WatershedArts/Footfall#100]
Hi,

How can I save detection moment's photo.

**Comment by DHaylock** [comment]
Add 

`ofSaveScreen(ofGetTimestampString()+".png");`

To the following lines 
[ofApp.cpp 88](https://github.com/WatershedArts/Footfall/blob/master/Footfall/src/ofApp.cpp#L88)
[ofApp.cpp 79](https://github.com/WatershedArts/Footfall/blob/master/Footfall/src/ofApp.cpp#L79)

Best
