### ISSUE TITLE
Problem Compiling Footfall Rpi3

### ISSUE THREAD

**Issue by thiesuh** [WatershedArts/Footfall#103]
Dear,

I am running in to problems with compiling Footfall. I am trying to compile it on a raspberry pi 3 with Raspbian jessie.

PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

I succesfully installed openFrameworks 0.9.8 (http://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/)  and i can run the examples.

HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal openssl gtk+-3.0
Done!
make: Leaving directory '/home/pi/openFrameworks/libs/openFrameworksCompiled/project'

After installing the necessary addons for the Footall i get the following error while compiling
"‘glm’ does not name a type." Wich is solved with issue 82 (https://github.com/WatershedArts/Footfall/issues/82)
"git checkout origin/stable" Also i renamed the libs directory to libs-old. 

Everytime after compiling i do a "make clean" and "rm -r linuxarmv6l/"  to clean it up. 

I tried to compile with make and make -j3 but they both fail. 

make -j3
https://pastebin.com/aZV26QRF
make
https://pastebin.com/0sBP28vP

I hope you can help me i am stuck at the moment. 

Dirk

**Comment by DHaylock** [comment]
Hi Dirk,

See issue #107
