### ISSUE TITLE
/home/dev05/of_v0.9.8_linux64_release/addons/ofxHttpUtils/src/ofxHttpTypes.h:51:43: error: invalid initialization of reference of type ‘const string& {aka const std::__cxx11::basic_string<char>&}’ from expression of type ‘const boost::filesystem::path’    formFiles[fieldName] = ofToDataPath(path);

### ISSUE THREAD

**Issue by SourabhMane** [WatershedArts/Footfall#107]
Please help me in resolving this  problem, i m stuck on this compiling error for many days.

**Comment by Anand02** [comment]
ok exactly what is the probelem/error ?

**Comment by mikcox** [comment]
Same issue here.  openFrameworks 0.9.8, gcc/g++ version 4.9.2 on Jessie (Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux).  Anyone seen this before or know of a possible workaround?

Thanks!

**Comment by mikcox** [comment]
Okay, I was able to at least compile the app by changing the following line in `~/openFrameworks/addons/ofxHttpUtils/src/ofxHttpTypes.h`:
from
```
formFiles[fieldName] = ofToDataPath(path);
```
to
```
formFiles[fieldName] = ofToDataPath(path.string());
```

I assume that this will likely break something down the line, but that's a problem for another day.  At least Footfall is compiling for me now.  :)
