### ISSUE TITLE
Operating system

### ISSUE THREAD

**Issue by xeryuso** [WatershedArts/Footfall#11]
I'm pretty new in this rasberry thing infact i just bougt it to try your program cause i need cost efficent people counter.I have encountered some problems while compiling OF and the solutions on issues section didn't do it for me. I want to format the whole system and try from a fres os. There is a NOOBS file in rasberrypi.org site. They say it's making setup easy.If I use NOOBS version will it cause an issue with your program or will it be fine ?

**Comment by DHaylock** [comment]
HI @xeryuso,

No problems. 

[NOOBS](https://www.raspberrypi.org/documentation/installation/noobs.md) is like a container of loads of different OSs.

There will be a couple of options as you progress through the setup. Ideally you want to use the Raspbian distro, its probably the recommended one. If you check the link above, you'll see the options screen.

With regards to OF Compilation errors, I would update and upgrade the system. ie sudo apt-get update upgrade.

Then create a new issue and I'll help try figure out the problem.

Best

David
