### ISSUE TITLE
Raspberry Pi 3 B+ SD IMAGE

### ISSUE THREAD

**Issue by 0raid** [WatershedArts/Footfall#112]
Hello , i am try to compile it @ raspberry pi 3 B+ , but a lot errors , strange because the old version of Footfall was compiled and running without any problems , but the new version still not compiled with success! , so i think it will help a lot people here if someone upload the SD IMAGE for raspberry pi 3 , such i have many dedicated servers for my work , i will be happy to provide the hosting for the SD image

so anyone can share the SD IMAGE with footfall compiled and ready to run?

Thanks

**Comment by Ferni492** [comment]
Hi, could you please share the previos images you made for the rpi3??
