### ISSUE TITLE
Raspberri Pi 3 Compiling Error

### ISSUE THREAD

**Issue by nfernandezsanz** [WatershedArts/Footfall#113]
Hi, I have this error when compiling
In file included from /home/pi/openFrameworks/addons/ofxCv/src/ofxCv.h:9:0,
                 from /home/pi/openFrameworks/apps/Footfall/Footfall/src/TrackingManager.h:12,
                 from /home/pi/openFrameworks/apps/Footfall/Footfall/src/TrackingManager.cpp:7:
/home/pi/openFrameworks/addons/ofxCv/libs/ofxCv/include/ofxCv/Utilities.h:16:30: fatal error: ofVideoBaseTypes.h: No such file or directory
 #include "ofVideoBaseTypes.h"

**Comment by nfernandezsanz** [comment]
The solution was the new stable branch of ofxCv, then I had some errors with ofxHttpUtils which I solved with the "-gh-pages" version.

**Comment by Chesterguan** [comment]
Hi I got the same problem and where can I get the stable branch of ofxCv, you mean the link below ?
https://github.com/kylemcdonald/ofxCv

Thanks for your time
