### ISSUE TITLE
Compiling error Rpi 3B+ / CameraManager.cpp

### ISSUE THREAD

**Issue by TheCarnifex** [WatershedArts/Footfall#126]
Hello together

I work at a Zoo and want use this app for counting people insite our animal houses. 

I'm try to compile the app, but i run into a error on CameraManager.cpp MOG2 every time

> /home/pi/openFrameworks/apps/myApps/Footfall/src/CameraManager.cpp:43:9: error: ‘class cv::BackgroundSubtractorMOG2’ has no member named ‘setDouble’
  pMOG2->setDouble**("fTau",  _cameraConfig.shadowPixelRatio);
         ^~~~~~~~~
/home/pi/openFrameworks/apps/myApps/Footfall/src/CameraManager.cpp: In member function ‘void CameraManager::update()’:
/home/pi/openFrameworks/apps/myApps/Footfall/src/CameraManager.cpp:104:20: error: ‘class cv::BackgroundSubtractorMOG2’ has no member named ‘operator()’
    pMOG2->operator()(combinedMask,processedMog);
                    ^
/home/pi/openFrameworks/apps/myApps/Footfall/src/CameraManager.cpp:108:20: error: ‘class cv::BackgroundSubtractorMOG2’ has no member named ‘operator()’
    pMOG2->operator()(videoMatrix,processedMog);
                    ^
In file included from /home/pi/openFrameworks/apps/myApps/Footfall/src/CameraManager.h:20,
                 from /home/pi/openFrameworks/apps/myApps/Footfall/src/CameraManager.cpp:7:
/home/pi/openFrameworks/addons/ofxCvPiCam/src/ofxCvPiCam.h: At global scope:
/home/pi/openFrameworks/addons/ofxCvPiCam/src/ofxCvPiCam.h:200:13: warning: ‘void color_callback(MMAL_PORT_T*, MMAL_BUFFER_HEADER_T*)’ declared ‘static’ but never defined [-Wunused-function]
 static void color_callback(MMAL_PORT_T *, MMAL_BUFFER_HEADER_T *);
             ^~~~~~~~~~~~~~
/home/pi/openFrameworks/addons/ofxCvPiCam/src/ofxCvPiCam.h:201:13: warning: ‘void gray_callback(MMAL_PORT_T*, MMAL_BUFFER_HEADER_T*)’ declared ‘static’ but never defined [-Wunused-function]
 static void gray_callback(MMAL_PORT_T *, MMAL_BUFFER_HEADER_T *);
             ^~~~~~~~~~~~~
make[1]: *** [/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:217: obj/linuxarmv6l/Release/src/CameraManager.o] Fehler 1
make[1]: Verzeichnis „/home/pi/openFrameworks/apps/myApps/Footfall“ wird verlassen
make: *** [/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:129: Release] Fehler 2

I think the problem is that the version of OpenCv MOG2 has not more the commands "operator" and "setDouble". But i'm new at this business, so i need help.

i followed the instruction to compile "OF" on this Site https://openframeworks.cc/setup/raspberrypi/raspberry-pi-getting-started/
Next step https://github.com/WatershedArts/Footfall/blob/master/docs/rpi.md
Then https://github.com/WatershedArts/Footfall/blob/master/docs/compiling.md

Rpi is an - 3B+ with Rasbian Buster - Linux raspberrypi 4.19.118-v7+
OF version is - of_v0.11.0_linuxarmv6l_release

Anyone can help me out, i hope.

If more informations needed please tell me.

Thanks for all your work, a lot. And sorry about my terrible english, i'm from Switzerland.

Kind regards, Dave

**Comment by oliverhumpage** [comment]
Hi Dave,

Your English is great, no worries!

Unfortunately this project was written a long time ago, and probably will require some updates to make it work. It looks like you're compiling with OpenCV 3, but it was written for OpenCV 2. This is the first thing to try.

However, I will warn you that although this system can provide approximate data for averaging/reporting purposes, it won't be accurate enough for use for serious reasons such as Covid protection: the pi camera is too easily confused by shadows/lighting.

I would recommend using a wide-angle cctv camera + some sort of tensorflow-based classifier to detect people (and therefore count them). This will be far more accurate, data protection permitting.

Wishing you and your zoo the very best for your re-opening.
