### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by ghost** [WatershedArts/Footfall#14]
I have finally managed to compile and run the program. The people are written into the database. However, I can't display them in the webinterface. what am I doing wrong?
Many thanks for the help.

**Comment by DHaylock** [comment]
Hi @mo2sidefyn,

Are there any errors in the browser?

Best

**Comment by ghost** [comment]
When i refresh the page, i can see only zeros, no peoples in or out.

With the developper tools this message shows up:

GET http://localhost/upload.php?get&interval=900 net::ERR_CONNECTION_REFUSEDsend @ jquery-1.10.2.js:8706jQuery.extend.ajax @ jquery-1.10.2.js:8136updateValues @ main-events.js:246(anonymous function) @ main-events.js:311
jquery-1.10.2.js:8706 GET http://localhost/upload.php?get&interval=900 net::ERR_CONNECTION_REFUSEDsend @ jquery-1.10.2.js:8706jQuery.extend.ajax @ jquery-1.10.2.js:8136updateValues @ main-events.js:246(anonymous function) @ main-events.js:311

**Comment by DHaylock** [comment]
Hmm,

Where is your upload.php file stored?

Best

**Comment by oliverhumpage** [comment]
Just to butt in here: if your dev tools log says “connection refused” when accessing http://localhost/… then it means you don’t have a web server running on your machine (at least, not on port 80).

The idea is that you have a web server somewhere that runs PHP+MySQL, where a) the pi can send its results to and b) where you can access those results. Where that is doesn’t matter so long as the pi has it set in its config, and both you and the pi can get to it. “localhost” probably isn’t that place.

Cheers,

Oliver.

**Comment by ghost** [comment]
My upload.php is in the root of my web server. The web server is on the same pi and PHP + MySQL are both running...

**Comment by oliverhumpage** [comment]
> On 18 Feb 2016, at 11:28, mo2sidefyn notifications@github.com wrote:
> 
> My upload.php is in the root of my web server. The web server is on the same pi and PHP + MySQL are both running…

So the footfall app itself will send results to http://localhost/upload.php and that will work OK.

However, if your web browser _isn’t_ on the same pi - which it likely isn’t - then connecting to “localhost” won’t work! So you need to go to http://[the.ip.address.of.your.pi]/ to see the results in your browser.

Oliver.

**Comment by ghost** [comment]
if i use the browser on my PI and go to localhost/events.php, it shows undefined.
if i navigate to localhost/upload.php the page is blank.
if i use a second computer on the same network and go to ipadressofmypi/events.php, it shows only zero's and gives me the connectionerror.

when i run the app, it counts and writes all the data into the database.

**Comment by ghost** [comment]
I changed the path of the upload.php inside of the config and main-events.js to http://ipofmypi/upload.php.
now my errorlog in the browser shows:

Uncaught TypeError: Cannot read property 'peoplein' of undefinedupdateLabels @ main-events.js:194(anonymous function) @ main-events.js:253fire @ jquery-1.10.2.js:3048self.fireWith @ jquery-1.10.2.js:3160done @ jquery-1.10.2.js:8235callback @ jquery-1.10.2.js:8778

**Comment by oliverhumpage** [comment]
> if i use the browser on my PI and go to localhost/events.php, it shows undefined.

What shows “undefined”?

> if i navigate to localhost/upload.php the page is blank.

Yes - upload.php is purely for the uploading of data, it’s not meant to be viewed in a browser.

> if i use a second computer on the same network and go to ipadressofmypi/events.php, it shows only zero's and gives me the connectionerror.

What is on line 51 of main-events.js (the “url” line inside the function preLoadData())? If it’s localhost then that won’t work. Set the url to http://ipaddressofmypi/upload.php...

Oliver.

**Comment by ghost** [comment]
So i just started from scratch...
I reconfigured the whole system and rebuilt the app. On line 51 of main-events.js is http://ipaddressofmypi/upload.php

My Database is recording, but my timestamp is 0000-00-00 00:00:00 locationID 1 and event 1
After changing to %S " ofGetTimestampString("%Y-%m-%d %H:%M:%S"))" and recompiled. I've got a timecode!!
<img width="1552" alt="bildschirmfoto 2016-03-03 um 17 19 54" src="https://cloud.githubusercontent.com/assets/11172365/13500767/38b51f7a-e164-11e5-8cbe-4b9765197de3.png">
<img width="299" alt="bildschirmfoto 2016-03-03 um 17 26 06" src="https://cloud.githubusercontent.com/assets/11172365/13500970/11b705c2-e165-11e5-89b1-62491b9091c6.png">

But when i navigate to http://ipofmypi/events.php...
<img width="1790" alt="bildschirmfoto 2016-03-03 um 17 28 21" src="https://cloud.githubusercontent.com/assets/11172365/13501034/5ac84c9e-e165-11e5-8889-95c1c3fd1c0c.png">

What am i doing wrong?

**Comment by DHaylock** [comment]
Hi @mo2sidefyn 

Could you try this

http://ipofmypi/upload.php?get&interval=3600

What comes back?

**Comment by ghost** [comment]
In safari nothing.
But with chrome:  Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by DHaylock** [comment]
Hi @mo2sidefyn 

Can you check your php log?

I think if you are using your pi as an apache server it will be /var/www/logs/apache/

**Comment by ghost** [comment]
[Thu Mar 03 16:42:13.184307 2016] [:error] [pid 920] [client 000.000.00.00:00000] PHP Notice:  Undefined variable: runningtotalin in /var/www/html/upload.php on line 96

This error fills the entire log...

**Comment by DHaylock** [comment]
Hi @mo2sidefyn,

In the Upload.php 
Add in $runningtotalin = 0;
[Line 73 Upload.php](https://github.com/WatershedArts/Footfall/blob/master/Web/upload.php#L79)

That should resolve that error. Strange because that definitely should be in there.

Best

**Comment by ghost** [comment]
Strange, this line is in the code...
