### ISSUE TITLE
Pre-recorded Video

### ISSUE THREAD

**Issue by staurasi** [WatershedArts/Footfall#15]
Hello, I'm not familiar with openframeworks, and I'm an opencv newbie.
How can I modify your code to test it with prerecorded videos?

Many thanks.

**Comment by DHaylock** [comment]
Hi @staurasi 

I've added a basic way of doing it in to the RPI2 Folder

[https://github.com/WatershedArts/Footfall/commit/3209b14dea50d3e847228cd37458b2dae2cb2178](https://github.com/WatershedArts/Footfall/commit/3209b14dea50d3e847228cd37458b2dae2cb2178)

Hope it Helps

**Comment by staurasi** [comment]
Actually I still have an RPI1, but it will be very easy for me to port the changes accordingly.
Many thanks!
