### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by EmreDemirci** [WatershedArts/Footfall#16]
Hi I have issues while building the app on RPI2 (Armv7l), using Jessie.
I have compiled OF v0.9 withouth any errors but when I tried to make run the RPi2 folder on my apps folder there were some errors. I tried to make clean and then make run but result were same. Could there be something Im missing ?

In file included from /home/pi/openFrameworks/addons/ofxCvPiCam/libs/mmal/src/interface/mmal/util/mmal_graph.c:32:0:
/home/pi/openFrameworks/addons/ofxCvPiCam/libs/mmal/src/interface/mmal/core/mmal_port_private.h: At top level:
/home/pi/openFrameworks/addons/ofxCvPiCam/libs/mmal/src/interface/mmal/core/mmal_port_private.h:93:67: error: unknown type name ‘MMAL_CLOCK_PAYLOAD_T’
 typedef void (_MMAL_PORT_CLOCK_EVENT_CB)(MMAL_PORT_T *port, const MMAL_CLOCK_PAYLOAD_T *event);
                                                                   ^
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:360: recipe for target '/home/pi/openFrameworks/addons/obj/linuxarmv7l/Release/ofxCvPiCam/libs/mmal/src/interface/mmal/util/mmal_graph.o' failed
make[1]: *_\* [/home/pi/openFrameworks/addons/obj/linuxarmv7l/Release/ofxCvPiCam/libs/mmal/src/interface/mmal/util/mmal_graph.o] Error 1
make[1]: Leaving directory '/home/pi/openFrameworks/apps/myApps/RPi2'
/home/pi/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:126: recipe for target 'Release' failed
make: **\* [Release] Error 2

**Comment by DHaylock** [comment]
Hi @MorPatates 

Thats the MMAL Issue.

You need to move the libs that come with the ofxCvPiCam addon.

See this [ReadMe](https://github.com/WatershedArts/Footfall/blob/master/ReadMe.md) it tells you how to move them.

Or see

[https://github.com/orgicus/ofxCvPiCam/issues/3](https://github.com/orgicus/ofxCvPiCam/issues/3)
