### ISSUE TITLE
using HOG method?

### ISSUE THREAD

**Issue by raditv** [WatershedArts/Footfall#24]
any sample of using hog method for tracking and detection?

**Comment by DHaylock** [comment]
There should be a sample of the HOG Detector in the openCV download package.
These might help.
[Hog Detector](https://chrisjmccormick.wordpress.com/2013/05/09/hog-person-detector-tutorial/)
[People Detector](http://www.magicandlove.com/blog/2011/08/26/people-detection-in-opencv-again/)
