### ISSUE TITLE
JavaScript Error

### ISSUE THREAD

**Issue by bluewookie88** [WatershedArts/Footfall#26]
When I load the events.php in Safari I get the following error: 

*_updateLabelsmain-events.js.pagespeed.jm.kMjyphLZsl.js:15TypeError: undefined is not an object *_

(evaluating 'data[data.length-1].peoplein')
updateLabelsmain-events.js.pagespeed.jm.kMjyphLZsl.js:14
(anonymous function)main-events.js.pagespeed.jm.kMjyphLZsl.js:23
firejquery-1.10.2.js:3047
fireWithjquery-1.10.2.js:3159
donejquery-1.10.2.js:8234
callbackjquery-1.10.2.js:8777

Does this mean the JSON file is not formatted correctly?  I cannot figure out what this means in context of this javascript file.

**Comment by DHaylock** [comment]
I cant seem to replicate this have you tried it in chrome
