### ISSUE TITLE
Drawing contour lines in original image

### ISSUE THREAD

**Issue by davidw212** [WatershedArts/Footfall#29]
Great app, but this seems to defeat me. The syntax is different from the opencv tutorials.

Please could you say how you drew the box and border around the identified blob in your top left image??

http://blogs.wcode.org/wp-content/uploads/2015/03/footfallgif.gif

**Comment by DHaylock** [comment]
Hi @davidw212 

No problems. The syntax isnt far off.
To draw the contours. You call contourFinder.draw(); this should draw the found blobs at (0,0).

Best

**Comment by davidw212** [comment]
Sorry Ive tried for a few weeks and still cant get the video output showing in colour and with the two blob borders.

I can get the greyscale frames displayed, and a circle on the midpoint of the blob, but not an outline boundary

Please could you give an indication of which section needs amending.

thanks
