### ISSUE TITLE
Documentation link dont work

### ISSUE THREAD

**Issue by mhkiyani2000** [WatershedArts/Footfall#34]
hello sir
the bellow link dont work
https://github.com/WatershedArts/Footfall/blob/master/docs/rpi.md

i cant download footfall document  in github

**Comment by igordutra** [comment]
The previous version of the readme file has more details than the current one. You can access it here:

https://github.com/WatershedArts/Footfall/commit/ec23d5169cf30cc0149ce4e9c7185d171c38a9ca

**Comment by DHaylock** [comment]
Hi both 

Have updated the repo

Best
