### ISSUE TITLE
Threaded live view unfiltered/Threaded Masking Not working

### ISSUE THREAD

**Issue by johnwestintx** [WatershedArts/Footfall#35]
Any way to get the threaded version to show a second screen of the camera that isn't masked or filtered?  I was able to get it with the RPi2 version, but not in the Threaded Version. 

Also, I was unable to get it to change the mask using the JSON config for Threaded as well.  

Thanks

**Comment by DHaylock** [comment]
Hi @johnwestintx 

See #38 

Best 

David
