### ISSUE TITLE
Video file playback problem

### ISSUE THREAD

**Issue by openedhardware** [WatershedArts/Footfall#38]
Hi, David.
At first, thanks for your great work on people counting!!!

I have been working with your code for 2 months to find proper config parameters in config.xml.
I have realized that it is very hard to config them without video playback.

I have analyzed your source code of RPi2 for video file playback.
But unfortunately, I cannot see the video output on the screen when APP is running.

I am wondering if you could solve this problem.

Thanks.

**Comment by mhkiyani2000** [comment]
hello
i can analyzed source code of RPI2 but cant see output on the screen,too
you find soultion for this problem??
thanks

**Comment by DHaylock** [comment]
Hi @openedhardware and @mhkiyani2000,

Cheers.

On line https://github.com/WatershedArts/Footfall/blob/master/RPi2/src/ofApp.cpp#L265
you need to add the following.

`drawMat(frame, 320, 0,320,240);`

This should draw the Video/Camera texture to the Screen.

Then set the GL Window to 640,240
https://github.com/WatershedArts/Footfall/blob/master/RPi2/src/main.cpp#L7

`ofSetupOpenGL(640,240, OF_WINDOW);`

Hope it helps

David
