### ISSUE TITLE
 did you run the latest install_dependencies.sh?.  Stop.

### ISSUE THREAD

**Issue by nc01315** [WatershedArts/Footfall#47]
I am installing open framework on my RPI2 and RPi3 , both had the same issue , I don't know why it gave me such error (I did install the dependency)

pi@raspberrypi:~/of_v0.8.4_linuxarmv7l_release/scripts/linux/debian $ sudo ./install_dependencies.sh
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie InRelease
0% [InRelease gpgv 13.2 kB]
Hit http://archive.raspberrypi.org jessie/main armhf Packages
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Hit http://mirrordirector.raspbian.org jessie/non-free armhf Packages
Hit http://mirrordirector.raspbian.org jessie/rpi armhf Packages
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB  
Ign http://archive.raspberrypi.org jessie/main Translation-en  
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB  
Ign http://archive.raspberrypi.org jessie/ui Translation-en  
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Reading package lists... Done  
detecting latest gstreamer version
Package: libgstreamer1.0-dev
Source: gstreamer1.0
Version: 1.4.4-2
Architecture: armhf
Maintainer: Maintainers of GStreamer packages pkg-gstreamer-maintainers@lists.alioth.debian.org
Installed-Size: 4195
Depends: libgstreamer1.0-0 (= 1.4.4-2), libc6-dev | libc-dev, pkg-config, libglib2.0-dev, libc6 (>= 2.4), libglib2.0-0 (>= 2.32), gir1.2-gstreamer-1.0 (= 1.4.4-2)
Recommends: debhelper
Suggests: gstreamer1.0-doc
Homepage: http://gstreamer.freedesktop.org
Priority: optional
Section: libdevel
Filename: pool/main/g/gstreamer1.0/libgstreamer1.0-dev_1.4.4-2_armhf.deb
Size: 1159970
SHA256: 71f43771bc11244e08e9fdff6570077670be04ec4d45aa5f82832d935f895f07
SHA1: f6a0f385c3664651e0f94161b7ae16ffd3fa7ab1
MD5sum: ea8aacdb8e731fd2460f484468d134de
Description: GStreamer core development files
 GStreamer is a streaming media framework, based on graphs of filters
 which operate on media data.  Applications using this library can do
 anything from real-time sound processing to playing videos, and just
 about anything else media-related.  Its plugin-based architecture means
 that new data types or processing capabilities can be added simply by
 installing new plug-ins.
 .
 This package contains development files for the core library and
 elements.
Description-md5: de1692260510350a48f76ec91eae40a9

selecting gstreamer 1.0
detecting latest gtk version
Package: libgtk-3-dev
Source: gtk+3.0
Version: 3.14.5-1+deb8u1rpi1rpi1g
Architecture: armhf
Maintainer: Debian GNOME Maintainers pkg-gnome-maintainers@lists.alioth.debian.org
Installed-Size: 10093
Depends: libgtk-3-0 (= 3.14.5-1+deb8u1rpi1rpi1g), gir1.2-gtk-3.0 (= 3.14.5-1+deb8u1rpi1rpi1g), libgtk-3-common, dconf-gsettings-backend | gsettings-backend, libglib2.0-dev (>= 2.41.2), libgdk-pixbuf2.0-dev (>= 2.27.1), libpango1.0-dev (>= 1.36.7), libatk1.0-dev (>= 2.7.5), libatk-bridge2.0-dev, libcairo2-dev (>= 1.10.0), libx11-dev, libxext-dev, libxinerama-dev, libxi-dev, libxrandr-dev, libxcursor-dev, libxfixes-dev, libxcomposite-dev, libxdamage-dev, pkg-config (>= 0.26-1), libwayland-dev (>= 1.4.0), libxkbcommon-dev
Suggests: libgtk-3-doc
Multi-Arch: same
Homepage: http://www.gtk.org/
Priority: optional
Section: libdevel
Filename: pool/main/g/gtk+3.0/libgtk-3-dev_3.14.5-1+deb8u1rpi1rpi1g_armhf.deb
Size: 887440
SHA256: 939766ccd1cd0781be284d969d1d300fc7f9d05c2568381219a9e23388b4d763
SHA1: f3a5ce8b6db4324ad8bdd14e9fc5dbbaffa8bd58
MD5sum: 13f47e4e44824b47124f1225c4807720
Description: development files for the GTK+ library
 GTK+ is a multi-platform toolkit for creating graphical user
 interfaces. Offering a complete set of widgets, GTK+ is suitable
 for projects ranging from small one-off tools to complete application
 suites.
 .
 This package contains the header and development files which are
 needed for building GTK+ applications.
Description-md5: 5e247317651e3625eb226ee49f0cfec7

Package: libgtk-3-dev
Source: gtk+3.0
Version: 3.14.5-1+deb8u1
Architecture: armhf
Maintainer: Debian GNOME Maintainers pkg-gnome-maintainers@lists.alioth.debian.org
Installed-Size: 9993
Depends: libgtk-3-0 (= 3.14.5-1+deb8u1), gir1.2-gtk-3.0 (= 3.14.5-1+deb8u1), libgtk-3-common, dconf-gsettings-backend | gsettings-backend, libglib2.0-dev (>= 2.41.2), libgdk-pixbuf2.0-dev (>= 2.27.1), libpango1.0-dev (>= 1.36.7), libatk1.0-dev (>= 2.7.5), libatk-bridge2.0-dev, libcairo2-dev (>= 1.10.0), libx11-dev, libxext-dev, libxinerama-dev, libxi-dev, libxrandr-dev, libxcursor-dev, libxfixes-dev, libxcomposite-dev, libxdamage-dev, pkg-config (>= 0.26-1), libwayland-dev (>= 1.4.0), libxkbcommon-dev
Suggests: libgtk-3-doc
Multi-Arch: same
Homepage: http://www.gtk.org/
Priority: optional
Section: libdevel
Filename: pool/main/g/gtk+3.0/libgtk-3-dev_3.14.5-1+deb8u1_armhf.deb
Size: 883238
SHA256: 47a73ae093398de45de5a159b361c70c12aa970b9d293d510f4db8e4a4a6ecfe
SHA1: d59ca0b71df6c12ad9503ef08660d3b21824d73d
MD5sum: 9c771c4a76d169b5f2de3b8975b73d6b
Description: development files for the GTK+ library
 GTK+ is a multi-platform toolkit for creating graphical user
 interfaces. Offering a complete set of widgets, GTK+ is suitable
 for projects ranging from small one-off tools to complete application
 suites.
 .
 This package contains the header and development files which are
 needed for building GTK+ applications.
Description-md5: 5e247317651e3625eb226ee49f0cfec7

selecting gtk 3
installing OF dependencies
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'libsndfile1-dev' instead of 'libsndfile-dev'
g++ is already the newest version.
g++ set to manually installed.
libfreetype6-dev is already the newest version.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-argparse : Depends: python2.6 but it is not installable
E: Unable to correct problems, you have held broken packages.
error installing dependencies, there could be an error with your internet connection
if the error persists, please report an issue in github: http://github.com/openframeworks/openFrameworks/issues
pi@raspberrypi:~/of_v0.8.4_linuxarmv7l_release/scripts/linux/debian $ 
pi@raspberrypi:~/of_v0.8.4_linuxarmv7l_release/scripts/linux/debian $ cd ~/of_v0.8.4_linuxarmv7l_release/examples/3d/3DPrimitivesExample/
pi@raspberrypi:~/of_v0.8.4_linuxarmv7l_release/examples/3d/3DPrimitivesExample $ make
checking pkg-config libraries:   cairo zlib gstreamer-app-0.10 gstreamer-0.10 gstreamer-video-0.10 gstreamer-base-0.10 libudev freetype2 fontconfig sndfile openal openssl libpulse-simple alsa glesv1_cm glesv2 egl 
../../../libs/openFrameworksCompiled/project/makefileCommon/config.shared.mk:260: **\* couldn't find some pkg-config packages, did you run the latest install_dependencies.sh?.  Stop.

**Comment by DHaylock** [comment]
It looks like you are trying to compile the armv7l package against armv6l.

Try reinstalling Jessie

Best
