### ISSUE TITLE
Matlab code

### ISSUE THREAD

**Issue by nc01315** [WatershedArts/Footfall#48]
Dear Footfall project developer ,

I wonder if you could provide and share the equivalent code in MATLAB programming language. (I am almost giving up on installing or setting up the current project on my RP2/3).

I can run simulink and/or MATLAB code from my Mac . I also installed hardware package for RP2/3 on the Matlab 2016a with no issue .

Thank you,

David

**Comment by DHaylock** [comment]
Hi @nc01315,

We built Footfall for C++, we don't have plans to convert this in to MATLAB
You can use some of the principles in the code in MATLAB.

Best
