### ISSUE TITLE
rotate the camera view

### ISSUE THREAD

**Issue by 0raid** [WatershedArts/Footfall#54]
Hello - nice project!

one quick question , is it possible to rotate the camera view ???

i have just setup this on my store , and i have install the camera the other-way , so  going in (is going out) and the opposite.

thanks

**Comment by DHaylock** [comment]
Hi @0raid 

You should be able to flip the camera view using this line.

[https://github.com/WatershedArts/Footfall/blob/master/RPi/src/ofApp.cpp#L98](https://github.com/WatershedArts/Footfall/blob/master/RPi/src/ofApp.cpp#L98)

Hope this helps

David

**Comment by 0raid** [comment]
hello DHaylock!

thanks for you fast reply! it works pefect! thanks again

one more question is it possible to change the position of the counting line???? 

thanks again!

george

**Comment by DHaylock** [comment]
Hi @0raid 

Yeah so if you alter this config

[https://github.com/WatershedArts/Footfall/blob/master/RPi/bin/data/config.xml#L14](https://github.com/WatershedArts/Footfall/blob/master/RPi/bin/data/config.xml#L14)

Should work 

David
