### ISSUE TITLE
Debugging display output

### ISSUE THREAD

**Issue by paranoidsystems** [WatershedArts/Footfall#55]
Hi All,

My test pi3 is in place and counting people. I really need to change blob size and direction etc. but I only have access to the unit with ssh or VNC now so no HDMI to see the display. I understand over VNC you can't see the camera display because of the way the pi dumps this right to the video buffer. Is it possible to be able to stream or record this output? Ideally it would be nice to go to http://mypi.com:8080 or something and see the "display". I am not sure how else to debug my strange counts without seeing the output.

**Comment by DHaylock** [comment]
Hi @paranoidsystems,

We also had this issue on numerous deployments of Footfall. 
We cheated slightly by saving images directly from the screen every second while there was a blob in the camera view. That should give you a small sequence to play with.

You'll need to add this in ofSaveFrame(false);

Hope this helps

**Comment by paranoidsystems** [comment]
That should do :) will try it out in a bit.
