### ISSUE TITLE
Data logging in csv format

### ISSUE THREAD

**Issue by PRITIAEC10** [WatershedArts/Footfall#56]
Can someone help me to create a log file of no.of people in and out in csv format?

**Comment by DHaylock** [comment]
Use the [ofxCsv](https://github.com/paulvollmer/ofxCsv) addon. Everytime you get an event of people coming in or out i.e 

[https://github.com/WatershedArts/Footfall/blob/master/RPi2/src/ofApp.cpp#L199](https://github.com/WatershedArts/Footfall/blob/master/RPi2/src/ofApp.cpp#L199)
or
[https://github.com/WatershedArts/Footfall/blob/master/RPi2/src/ofApp.cpp#L222](https://github.com/WatershedArts/Footfall/blob/master/RPi2/src/ofApp.cpp#L222)

Just use the addRow function in ofxCsv.
