### ISSUE TITLE
How to compile footfall for desktop?

### ISSUE THREAD

**Issue by PRITIAEC10** [WatershedArts/Footfall#57]

**Comment by DHaylock** [comment]
Hi 

What OS are you using?

**Comment by PRITIAEC10** [comment]
I am using UBUNTU 16.04 LTS, 64 BIT

**Comment by DHaylock** [comment]
Hi @PRITIAEC10,

Download and compile the Linux Version of openFrameworks. [Link](http://openframeworks.cc/setup/linux-install/) 

Pull the necessary repos. Removing ofxCvPiCam.
You will need to remove it from the addons.make file aswell.

Follow the [compiling instructions](https://github.com/WatershedArts/Footfall/blob/master/docs/compiling.md)

In CameraManager.h you'll need to remove the references to ofxCvPiCam and Uncomment the USE_WEBCAM Macro.

Best
