### ISSUE TITLE
[ error ] Can't upload due to no network

### ISSUE THREAD

**Issue by Hardold** [WatershedArts/Footfall#64]

**Comment by Hardold** [comment]
Any suggestion? My operating system is Ubuntu 14.04 64bit

**Comment by Hardold** [comment]
![image](https://cloud.githubusercontent.com/assets/12985844/23330499/1d014268-fb8a-11e6-881f-40067083c173.png)

**Comment by DHaylock** [comment]
Hi @Hardold,

What's in your Config File?

Best

**Comment by DHaylock** [comment]
Hi @Hardold,

Try pulling the latest version.
I hadn't realised the upload.php didnt have a check handler. So always returns false.

Hopefully that should work.

Best

**Comment by Hardold** [comment]
Hi @DHaylock,
    Perfect solution!
    Thinks!
