### ISSUE TITLE
If two people walk side by side or one after the other, which parameter should I adjust?

### ISSUE THREAD

**Issue by Hardold** [WatershedArts/Footfall#65]

**Comment by DHaylock** [comment]
Hi @Hardold,

Are they recording as one person or two?

Best

**Comment by Hardold** [comment]
They are recording as one person.I'm confused .Which parameters should I adjust?

Best

**Comment by PRITIAEC10** [comment]
Blobsize is to be adjusted

**Comment by DHaylock** [comment]
If you have two people walking in side by side, footfall for the time being cant segment them. So i would adjust the maxblobsize to 3/4 the size of the camerawidth. Adjust the midblobsize variable to 1.5x size of minblobsize.

**Comment by Hardold** [comment]
Hi,
@DHaylock 
  What parameters to adjust maxblobsize, midblobsize and minblobsize? Thinks a lot ! 
`"minsizeone": 10,
"minsizetwo":30,
"minsizethree": 150`?

**Comment by DHaylock** [comment]
Tracking config: minblobsize and maxblobsize for the contour finder. min,mid,max size for the event reporting is if the blob can be considered to be bigger than one person.

**Comment by Hardold** [comment]
minblobsize is "minarea"?
maxblobsize is"maxarea"?
What is the relationship between( "minsizeone", "minsizetwo", "minsizethree" )and( "minarea" and "maxarea") ?  My picture size is 640*480. How to set them?

**Comment by DHaylock** [comment]
Hi @Hardold,

Yes.

The [Configuration.md](https://github.com/WatershedArts/Footfall/blob/master/docs/configuration.md) should explain all the parameters.

Best
