### ISSUE TITLE
[warning] ofGstVideoUtils: update(): ofGstVideoUtils not loaded

### ISSUE THREAD

**Issue by Hardold** [WatershedArts/Footfall#66]
When I define USE_VIDEO, I can't open the video,and this warning appears.

**Comment by DHaylock** [comment]
Have you changed this [line](https://github.com/WatershedArts/Footfall/blob/master/Footfall/src/CameraManager.cpp#L47) to be the name of your calibration testFootage

**Comment by Hardold** [comment]
Hi, @DHaylock 
    I solved it,Thinks!
