### ISSUE TITLE
How to adjust the length of the rectangle of the green circle?

### ISSUE THREAD

**Issue by Hardold** [WatershedArts/Footfall#68]
Hi, @DHaylock 
    How to adjust the length of the rectangle of the green circle? Thinks a lot!
![iun 8tui i zi ny8q6](https://cloud.githubusercontent.com/assets/12985844/23395725/24d84480-fdcb-11e6-9ec2-9d93bef429f9.png)

**Comment by DHaylock** [comment]
Change the camera width to be the same size as your video's width.

**Comment by DHaylock** [comment]
And height. Then alter the offset and the startposy to be half the camera height

**Comment by DHaylock** [comment]
Check the [configuration.md](./docs/configuration.md)

**Comment by Hardold** [comment]
I get it !Thinks!
![s36s f9y28 elbj dzf p](https://cloud.githubusercontent.com/assets/12985844/23395884/e7527d78-fdcb-11e6-9a8f-43a96b61f511.png)
