### ISSUE TITLE
If I want to remove the interference of the picture, what parameters should I adjust?

### ISSUE THREAD

**Issue by Hardold** [WatershedArts/Footfall#69]
Hi,
 @DHaylock 
![0t v07dc6 b0e0 q2mr 5w](https://cloud.githubusercontent.com/assets/12985844/23396626/a7bd9554-fdcf-11e6-9dce-a62e57fc8c5e.png)

**Comment by DHaylock** [comment]
Increase history in the cameraconfig and play around with the mogthreshold. Generally, the brighter the floor the higher the threshold should be.
