### ISSUE TITLE
How to change the font size? Thinks a lot!

### ISSUE THREAD

**Issue by Hardold** [WatershedArts/Footfall#71]
![05od m1 vkt h_a14 p91](https://cloud.githubusercontent.com/assets/12985844/23578803/10589a3a-011a-11e7-9467-7f2bf4041d9c.png)

**Comment by DHaylock** [comment]
Hi @Hardold,

Implement some of the code from here (openFrameworks/examples/graphics/fontsExample) in Footfall.
