### ISSUE TITLE
Rotate Tracking Area?

### ISSUE THREAD

**Issue by CrossPT** [WatershedArts/Footfall#77]
Hi.
First of all thanks for this amazing code!
I'm currently testing the footfall of this area 
![Area](https://s4.postimg.org/y5zqwq9zx/IMG_20170315_145701.jpg)

I want to count the footfall on people (rotate the tracking bar) without changing the position of the RPi, like this:
![Test](https://s4.postimg.org/8bpy6y9zx/IMG_20170315_145711.jpg)

Is it possible?

**Comment by DHaylock** [comment]
Hi @CrossPT,

Yeah totally possible though you will need to alter the source code. I haven't had time to implement this properly. But for now. Compile these files. Essentially in your config.json. The code will look for a 0 in either of the startposition parameters. If it finds 0 in the y it will flip the orientation of tracking. Just tried it on my machine seems to be ok may want to refine it abit.

[Archive.zip](https://github.com/WatershedArts/Footfall/files/845221/Archive.zip)

Hope it helps.

Best

**Comment by CrossPT** [comment]
Thumbs up for the quick reply! 👍 
Will test and reply with the changes

**Comment by CrossPT** [comment]
Works like a a charm!

Maybe make a small change in code to flip the orientation of tracking. The startposition parameters may be arranged to one parameter only.

Something like this in config.json:
startpos: **value**,
landscape: **true/false**
