### ISSUE TITLE
All 0s in MySQL and no data on the report

### ISSUE THREAD

**Issue by RRikP** [WatershedArts/Footfall#8]
Hello, 
I am building this project for a non profit organization. I am beginner so please forgive me for my stupid questions and thanks a lot for sharing your hard work here. 
I have created a MySQL db and its pushing data to it. However I noticed that all of the data in phpMyAdmin is showing up with locationID=0 and event=0, and timestamp=0s. 
Also in the terminal i only see "200:count: < /br> Location: < /br> Raw Timestamp: "every time there is an in or out count comes in. 
 Any thoughts on what i am missing? Thank you in advance.

**Comment by DHaylock** [comment]
Hi @rrrikin,

I Pushed some changes yesterday that should solve this issue.
I forgot that I was using PDO to do the queries, so my_real_escape_string zeros the values.

Best
