### ISSUE TITLE
When I wear black, the contour finder doesn't detect me,and the tracker can't track me .

### ISSUE THREAD

**Issue by Hardold** [WatershedArts/Footfall#81]
Hi, 
   When I wear black, the contour finder doesn't detect me,and the tracker can't track me .Any suggestions? Thinks a lot !

**Comment by Hardold** [comment]
![t vyw64b1ry _ea 7 _ 1 4](https://cloud.githubusercontent.com/assets/12985844/24243731/10e3605c-0ff7-11e7-8a8b-a7ba8f331609.png)

**Comment by Hardold** [comment]
![1234](https://cloud.githubusercontent.com/assets/12985844/24277523/8bea6486-1078-11e7-9247-14b22e50fa4e.png)

**Comment by DHaylock** [comment]
play around with the mogthreshold. 
There is a new version of Footfall coming with a Gui so you can tweak values.

**Comment by randomly123** [comment]
https://github.com/patnealcodes/jsongui

can probably use this to make a webapp/ mobile thingie
