### ISSUE TITLE
Nothing happens if I change some values in config

### ISSUE THREAD

**Issue by prastut** [WatershedArts/Footfall#90]
Changing the values of: 

```
"CameraConfig": {
			"flipvertically": false,
			"trackshadows": true,
			},
```
```
"TrackingConfig": {
			"flipvertically":false,
			
		},

``` 

Nothing happens. It shows the previous config only.

**Comment by screwu666** [comment]
got same issue with startposx axis and some other parameters. Cannot move the tracking line on X axis

**Comment by randomly123** [comment]
I got the same issue as screwu above. I was only able to enlarge the line on the X axis by changing the CAMERAWIDTH parameter.
